# Eggs.Variant
#
# Copyright Agustin K-ballo Berge, Fusion Fenix 2014-2016
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

language: cpp
sudo: false

matrix:
  include:
    # clang-3.5
    - env: CLANG_VERSION=3.5 CXX_FLAGS="-std=c++11" BUILD_TYPE=Debug
      os: linux
      addons: &clang35
        apt:
          packages:
            - clang-3.5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - env: CLANG_VERSION=3.5 CXX_FLAGS="-std=c++11" BUILD_TYPE=Release
      os: linux
      addons: *clang35

    - env: CLANG_VERSION=3.5 CXX_FLAGS="-std=c++14" BUILD_TYPE=Debug
      os: linux
      addons: *clang35

    - env: CLANG_VERSION=3.5 CXX_FLAGS="-std=c++14" BUILD_TYPE=Release
      os: linux
      addons: *clang35

    # clang-3.6
    - env: CLANG_VERSION=3.6 CXX_FLAGS="-std=c++11" BUILD_TYPE=Debug
      os: linux
      addons: &clang36
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - env: CLANG_VERSION=3.6 CXX_FLAGS="-std=c++11" BUILD_TYPE=Release
      os: linux
      addons: *clang36

    - env: CLANG_VERSION=3.6 CXX_FLAGS="-std=c++14" BUILD_TYPE=Debug
      os: linux
      addons: *clang36

    - env: CLANG_VERSION=3.6 CXX_FLAGS="-std=c++14" BUILD_TYPE=Release
      os: linux
      addons: *clang36

    # gcc-4.9
    - env: GCC_VERSION=4.9 CXX_FLAGS="-std=c++11" BUILD_TYPE=Debug
      os: linux
      addons: &gcc49
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=4.9 CXX_FLAGS="-std=c++11" BUILD_TYPE=Release
      os: linux
      addons: *gcc49

    - env: GCC_VERSION=4.9 CXX_FLAGS="-std=c++1y" BUILD_TYPE=Debug
      os: linux
      addons: *gcc49

    - env: GCC_VERSION=4.9 CXX_FLAGS="-std=c++1y" BUILD_TYPE=Release
      os: linux
      addons: *gcc49

    # gcc-5
    - env: GCC_VERSION=5 CXX_FLAGS="-std=c++11" BUILD_TYPE=Debug
      os: linux
      addons: &gcc5
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - env: GCC_VERSION=5 CXX_FLAGS="-std=c++11" BUILD_TYPE=Release
      os: linux
      addons: *gcc5

    - env: GCC_VERSION=5 CXX_FLAGS="-std=c++14" BUILD_TYPE=Debug
      os: linux
      addons: *gcc5

    - env: GCC_VERSION=5 CXX_FLAGS="-std=c++14" BUILD_TYPE=Release
      os: linux
      addons: *gcc5

    # Xcode 7
    - env: CXX_FLAGS="-std=c++11" BUILD_TYPE=Debug
      os: osx
      osx_image: xcode7
      addons: &xcode7

    - env: CXX_FLAGS="-std=c++11" BUILD_TYPE=Release
      os: osx
      osx_image: xcode7
      addons: *xcode7

    - env: CXX_FLAGS="-std=c++14" BUILD_TYPE=Release
      os: osx
      osx_image: xcode7
      addons: *xcode7

    - env: CXX_FLAGS="-std=c++14" BUILD_TYPE=Release
      os: osx
      osx_image: xcode7
      addons: *xcode7

branches:
  only:
    - master
    - develop

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi

  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install cmake; fi

install:
  - mkdir build
  - cd build
  - export CXX_FLAGS="${CXX_FLAGS} -Wall -Wextra -Werror"
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" ..

script: make tests -k

notifications:
  email: false
