# Eggs.Variant
#
# Copyright Agustin K-ballo Berge, Fusion Fenix 2014-2017
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

language: cpp
sudo: false

matrix:
  include:
    # clang-3.9
    - env: VERSION=3.9 CXX_VERSIONS="11;14;1z"
      compiler: clang
      os: linux
      addons:
        apt:
          packages:
            - clang-3.9
            - libstdc++-6-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9

    # clang-4
    - env: VERSION=4.0 CXX_VERSIONS="11;14;1z"
      compiler: clang
      os: linux
      addons:
        apt:
          packages:
            - clang-4.0
            - libstdc++-6-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    # clang-5
    - env: VERSION=5.0 CXX_VERSIONS="11;14;17"
      compiler: clang
      os: linux
      addons:
        apt:
          packages:
            - clang-5.0
            - libstdc++-7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    # gcc-5
    - env: VERSION=5 CXX_VERSIONS="11;14;1z"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    # gcc-6
    - env: VERSION=6 CXX_VERSIONS="11;14;1z"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    # gcc-7
    - env: VERSION=7 CXX_VERSIONS="11;14;17"
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    # Xcode 7.3
    - env: CXX_VERSIONS="11;14;1z"
      compiler: clang
      os: osx
      osx_image: xcode7.3

    # Xcode 8.3
    - env: CXX_VERSIONS="11;14;1z"
      compiler: clang
      os: osx
      osx_image: xcode8.3

    # Xcode 9.1
    - env: CXX_VERSIONS="11;14;1z"
      compiler: clang
      os: osx
      osx_image: xcode9.1

branches:
  only:
    - master
    - develop

before_install:
  - |
    if [ -n "${VERSION}" ]; then
      export CC="${CC}-${VERSION}"
      export CXX="${CXX}-${VERSION}"
    fi
  - export CXXFLAGS="-Wall -Wextra -Werror -pedantic-errors"
  - CXX_VERSIONS=(${CXX_VERSIONS//;/ })
  - BUILD_TYPES=(Debug Release)

install:
  - |
    for CXX_VERSION in "${CXX_VERSIONS[@]}"; do
      for BUILD_TYPE in "${BUILD_TYPES[@]}"; do
        BUILD_DIR="build-${CXX_VERSION}-${BUILD_TYPE}"
        mkdir "${BUILD_DIR}"
        pushd "${BUILD_DIR}"
        (
          set -ex
          export CXXFLAGS="${CXXFLAGS} -std=c++${CXX_VERSION}"
          cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" ..
        )
        popd
      done
    done

script:
  - |
    for CXX_VERSION in "${CXX_VERSIONS[@]}"; do
      for BUILD_TYPE in "${BUILD_TYPES[@]}"; do
        BUILD_DIR="build-${CXX_VERSION}-${BUILD_TYPE}"
        pushd "${BUILD_DIR}"
        (
          set -ex
          cmake --build . -- -j 2 -k
          ctest --output-on-failure
        )
        popd
      done
    done

notifications:
  email: false
